<?xml version="1.0"?>
<package format="3">
  <name>gapfollower</name>
  <version>0.1.0</version>
  <description>Reactive Follow-the-Gap using RS-LiDAR-16</description>

  <maintainer email="m2nyok2@hanyang.ac.kr">오민혁</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>pcl_conversions</depend>
  <depend>pcl_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
