dataset= 'CULane'
data_root= '' # Need to be modified before running
epoch= 50
batch_size= 32
optimizer= 'SGD'
learning_rate= 0.05
weight_decay= 0.0004
momentum= 0.9
scheduler= 'multi'
steps= [25,38]
gamma= 0.1
warmup= 'linear'
warmup_iters= 695
use_aux= False
griding_num= 100  # Reduced from 200 for thicker lanes
backbone= '18'
sim_loss_w= 0.0
shp_loss_w= 0.0
note= ''
log_path= ''
finetune= None
resume= None
test_model=''
test_work_dir = ''
tta=True
num_lanes= 4  # Increased from 2 to detect more lanes
var_loss_power= 2.0
auto_backup= True
num_row= 52  # Reduced from 72 for better thick lane detection
num_col= 60  # Reduced from 81 for better thick lane detection
train_width= 1600
train_height= 320
num_cell_row= 150  # Reduced from 200 to match griding_num
num_cell_col= 75   # Reduced from 100 for thicker lane detection
mean_loss_w= 0.03  # Slightly increased from 0.02
fc_norm= True
crop_ratio = 0.9   # Reduced from 1.0 to include more road area
