<?xml version="1.0"?>
<package format="2">
  <name>emergency</name>
  <version>0.1.0</version>
  <description>Emergency detector node for monitoring cluster distance</description>

  <maintainer email="ati0423@hanang.ac.kr">antel</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

